BINARY := 7a9b3b24-3e2f-4d5f-912d-8b7c1355629a

TA_TARGETS       ?= ta_arm64
CFG_TA_ARM64     ?= y
CFG_TA_ARM32     ?= n
CROSS_COMPILE    ?= aarch64-linux-gnu-

include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
